### ISSUE TITLE
Imitate how the icons look in iCloud links

### ISSUE THREAD

**Issue by atnbueno** [atnbueno/shortcut-icons#4]
Currently the CSS imitates the icon PNGs, but they are normally shown with a slight shadow and more rounded corners. Currently the pertinent CSS in iCloud links is this:
```css
main #shortcut-icon {
    width: 60px;
    height: 60px;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,.14);
    border-radius: 10px;
}
```
